### ISSUE TITLE
Running 'journal' module gets skipped

### ISSUE THREAD

**Issue by azec-pdx** [awslabs/aws-ec2rescue-linux#57]
Hi there,

I have pulled down `ec2rl` and trying to run with:

```
./ec2rl run --config-file=/var/tmp/ec2rl/2020-02-14T18_13_59.605550/configuration.cfg --only-modules=journal
```
When I run above, even as `sudo` I see that many modules are skipped.
The config file was created using 
```
./ec2rl menu-config
```

I would particularly like to run `journal` module as one of our EC2 instances failed both System Checks and Instance Checks at the same time and nothing is showing in AWS Personal Health Dashboard related to that event.

However running below I can see that `journal`  module is disabled for performance issues...

```
# ./ec2rl help journal
journal:
Gather journal output - Temporarily disabled due to performance impact
Requires sudo: False
Supports remediation: False
```

How can we enable particular modules one at a time? 
Also curious what is the quickest way to diagnose the issue with some default "good" configuration. 

Any help is appreciated !

Thank you !

**Comment by Drudenhaus** [comment]
Hi there,

>When I run above, even as sudo I see that many modules are skipped.

You can see the specific reason a module was skipped in the log (Main.log). For example:

```
2020-02-14T23:23:26CST main.py    INFO    : ----------------------------------------
2020-02-14T23:23:26CST main.py    INFO    : BEGIN PREDIAGNOSTICS
2020-02-14T23:23:26CST main.py    INFO    : ----------------------------------------
2020-02-14T23:23:26CST main.py    INFO    : prediagnostic/verify_metadata: not an instance; skipping
2020-02-14T23:23:26CST main.py    INFO    : module run/aptlog: Skipping. Reason: Not applicable to this distro.
...
```

> I would particularly like to run journal module as one of our EC2 instances failed both System Checks and Instance Checks at the same time and nothing is showing in AWS Personal Health Dashboard related to that event.

As you saw, we had disabled the journal module (in https://github.com/awslabs/aws-ec2rescue-linux/pull/20). The journal module is simply a gather class module so you could copy the logs off the system some other way and accomplish the same task. However, since the instance status check failed, I presume you don't have access to it and have already stopped the instance and attached the volume to a functioning instance for debugging so you could look at the logs directly that way.

>How can we enable particular modules one at a time?

You can use the --only-modules arg to run a specific set of modules (like in your first example). You must still satisfy all the constraints though, whether that's distribution applicability, required arguments, sudo, etc.

>Also curious what is the quickest way to diagnose the issue with some default "good" configuration.

You can get a decent spread of modules with --times=X --period=Y, but I recommend reviewing the modules and their required args. You can do this using the CLI menu or the module help.

**Comment by Drudenhaus** [comment]
Will close next week unless I hear back.

**Comment by gregbdunn** [comment]
Closing this and opening https://github.com/awslabs/aws-ec2rescue-linux/issues/63 for general discussion around the journal module and our long term plans.
